"""End-to-end integration tests for the HybriDock-Pep pipeline.

Two test suites are included:

TEST-02 — MDM2/p53 (existing wiring test):
  Uses a 3-atom placeholder receptor (receptor_tiny.pdb) placed 25 Å from the
  fixture poses.  Validates pipeline wiring only — not score sign or quality.
  The biological threshold (best hybrid_score < -3.0 kcal/mol) requires the
  real MDM2 receptor and is validated by scripts/benchmark.py instead.

TEST-03 — PepSet Crystal-Pose Tests (4 protein families):
  Uses real receptor pocket PDB files and crystal-structure reference poses
  drawn from the PepSet benchmark (families where RAPiDock was trained).
  These tests assert that the scoring pipeline produces physically meaningful
  Vina scores (< 0 kcal/mol) for crystal-quality poses — the minimum sanity
  bar for a correctly wired Vina installation.

  Families covered:
    pdz_1jq8  — PDZ domain      LAIYS        (5 residues,  easy, 1.4 Å X-ray)
    sh2_1jw6  — SH2 domain      MYWYPY       (6 residues,  easy, 1.93 Å)
    brd_3shb  — Bromodomain     ARTKQTA      (7 residues,  easy, 1.8 Å)
    cam_3bej  — Calmodulin      ERHKILHRLLQ  (11 residues, easy, 1.9 Å)

  These four families represent the highest-confidence region of RAPiDock's
  training distribution (PDZ, SH2, histone-reader, calmodulin IQ-motif) and
  are expected to yield negative Vina scores when docked with the crystal pose.

All tests are tagged @pytest.mark.slow — require Vina ≥ 1.2.5, ADFRsuite on
PATH (babel + prepare_receptor), and score-env fully installed.

Run with: pytest -m slow tests/test_e2e.py
"""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import NamedTuple

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# TEST-02: MDM2/p53 (pipeline wiring with placeholder receptor)
# ---------------------------------------------------------------------------


def _make_e2e_config(output_dir: Path):
    """Build a DockConfig for MDM2/p53 using the receptor_tiny.pdb placeholder.

    Uses receptor_tiny.pdb (3 ALA atoms) for pipeline wiring tests only.
    box_size=60 is required to cover extended backbone poses (~44 Å span).

    Args:
        output_dir: Destination directory for ranked_poses.csv, best_pose.pdb,
            run_metadata.json.

    Returns:
        Validated DockConfig instance.
    """
    from hybridock_pep.models import DockConfig

    return DockConfig(
        peptide_sequence="ETFSDLWKLLPE",
        receptor_path=FIXTURES_DIR / "receptor_tiny.pdb",
        site_coords=(26.4, 3.5, -5.6),
        # box_size=60 covers the full span of extended 12-mer backbone poses
        # (~44 Å) generated by RAPiDock without CONECT records, which babel
        # cannot connect into a single molecule. 30 Å is too small and causes
        # "ligand outside grid box" errors on most fixture poses.
        box_size=60.0,
        n_samples=25,
        output_dir=output_dir,
        seed=42,
    )


@pytest.mark.slow
class TestMDM2P53Integration:
    """Full pipeline integration test on the MDM2/p53 complex.

    Requires Vina, Meeko, ADFRsuite, and score-env fully installed.
    Skipped automatically when pytest is run without -m slow.
    """

    def test_pipeline_runs_end_to_end(self, tmp_path: Path) -> None:
        """Run the full pipeline on 25 MDM2/p53 fixture poses; assert outputs are correct.

        Validates pipeline wiring (TEST-02 structural checks):
          - ranked_poses.csv produced with required columns
          - best_pose.pdb written and non-empty
          - run_metadata.json has status="complete"
          - delta_g == hybrid_score in every row

        NOTE: The biological TEST-02 threshold (hybrid_score < -3.0 kcal/mol)
        is NOT checked here because receptor_tiny.pdb is a placeholder 25 Å
        from the fixture poses.  The threshold is validated by the benchmark
        suite against the real MDM2 receptor.
        """
        from hybridock_pep import driver

        poses_dir = FIXTURES_DIR / "mdm2_p53"
        cal_path = FIXTURES_DIR / "mdm2_calibration.json"
        output_dir = tmp_path / "mdm2_run"
        config = _make_e2e_config(output_dir)

        scored_poses, cluster_result = driver.run_dock(
            config=config,
            input_poses_dir=poses_dir,
            calibration_path=cal_path,
        )

        # --- Assert: ranked_poses.csv exists with correct structure ---
        csv_path = output_dir / "ranked_poses.csv"
        assert csv_path.exists(), "ranked_poses.csv must be created by Stage 4"

        rows = list(csv.DictReader(csv_path.open()))
        assert 1 <= len(rows) <= 10, (
            f"ranked_poses.csv should have 1–10 rows; got {len(rows)}"
        )

        required_cols = {
            "rank", "hybrid_score", "vina_score", "ad4_score",
            "entropy_correction", "delta_g", "cluster_id",
            "pose_filename", "is_ad4_anomaly", "is_clipped",
        }
        assert required_cols.issubset(rows[0].keys()), (
            f"Missing columns: {required_cols - rows[0].keys()}"
        )

        # --- Assert: hybrid_score is a finite float (scoring ran without crash) ---
        # The biological threshold (< -3.0 kcal/mol) requires the real MDM2
        # receptor; with receptor_tiny.pdb the Vina score is ~0 by design.
        best_hybrid = min(float(r["hybrid_score"]) for r in rows)
        assert isinstance(best_hybrid, float) and best_hybrid < 1e6, (
            f"hybrid_score is not a finite float: {best_hybrid}"
        )

        # --- Assert: best_pose.pdb exists and is non-empty ---
        best_pdb = output_dir / "best_pose.pdb"
        assert best_pdb.exists(), "best_pose.pdb must be written by Stage 4"
        assert best_pdb.stat().st_size > 0, "best_pose.pdb must not be empty"

        # --- Assert: run_metadata.json written with status=complete ---
        metadata_path = output_dir / "run_metadata.json"
        assert metadata_path.exists(), "run_metadata.json must exist"
        metadata = json.loads(metadata_path.read_text())
        assert metadata.get("status") == "complete", (
            f"run_metadata.json status should be 'complete', got {metadata.get('status')!r}"
        )

        # --- Assert: delta_g == hybrid_score in every row (D-04) ---
        for row in rows:
            assert row["delta_g"] == row["hybrid_score"], (
                f"delta_g ({row['delta_g']}) != hybrid_score ({row['hybrid_score']}) "
                f"for rank {row['rank']}"
            )


# ---------------------------------------------------------------------------
# TEST-03: PepSet crystal-pose tests
# ---------------------------------------------------------------------------


class _PepSetCase(NamedTuple):
    tag: str              # fixture subdirectory name
    pdb_id: str           # PDB accession (informational)
    family: str           # protein family (informational)
    peptide: str          # single-letter sequence
    site: tuple[float, float, float]  # binding site center (Å)
    box: float            # grid box edge length (Å)


# Binding site centres are computed as the Cα centroid of each reference
# peptide; box size adds 12 Å to the max Cα–Cα span across all heavy atoms.
_PEPSET_CASES: list[_PepSetCase] = [
    _PepSetCase(
        tag="pdz_1jq8",
        pdb_id="1JQ8",
        family="PDZ domain",
        peptide="LAIYS",
        site=(12.36, 21.26, 40.31),
        box=30.0,
    ),
    _PepSetCase(
        tag="sh2_1jw6",
        pdb_id="1JW6",
        family="SH2 domain",
        peptide="MYWYPY",
        site=(12.56, 32.23, 25.92),
        box=32.0,
    ),
    _PepSetCase(
        tag="brd_3shb",
        pdb_id="3SHB",
        family="Bromodomain / histone reader",
        peptide="ARTKQTA",
        site=(-12.52, 10.72, 13.38),
        box=32.0,
    ),
    _PepSetCase(
        tag="cam_3bej",
        pdb_id="3BEJ",
        family="Calmodulin / EF-hand",
        peptide="ERHKILHRLLQ",
        site=(29.16, 9.09, -0.39),
        box=35.0,
    ),
]


def _make_pepset_config(case: _PepSetCase, output_dir: Path):
    """Build a DockConfig for a PepSet crystal-pose case.

    Uses the real receptor pocket PDB and crystal reference peptide pose.
    AD4 scoring is included to test the full Vina+AD4 pipeline.

    Args:
        case: PepSet case specification.
        output_dir: Run output directory.

    Returns:
        Validated DockConfig instance.
    """
    from hybridock_pep.models import DockConfig

    return DockConfig(
        peptide_sequence=case.peptide,
        receptor_path=FIXTURES_DIR / case.tag / "receptor_pocket.pdb",
        site_coords=case.site,
        box_size=case.box,
        n_samples=1,
        output_dir=output_dir,
        seed=42,
        scoring={"vina", "ad4"},
    )


def _run_pepset_case(
    case: _PepSetCase,
    tmp_path: Path,
) -> tuple[list, dict, dict]:
    """Run the pipeline for a single PepSet case; return (rows, metadata, scored_poses).

    Args:
        case: PepSet test case.
        tmp_path: pytest tmp_path fixture for output isolation.

    Returns:
        (csv_rows, metadata_dict, {pose_idx: ScoredPose}) for downstream assertions.
    """
    from hybridock_pep import driver

    poses_dir = FIXTURES_DIR / case.tag
    cal_path = FIXTURES_DIR / "mdm2_calibration.json"
    output_dir = tmp_path / case.tag
    config = _make_pepset_config(case, output_dir)

    scored_poses, cluster_result = driver.run_dock(
        config=config,
        input_poses_dir=poses_dir,
        calibration_path=cal_path,
    )

    csv_path = output_dir / "ranked_poses.csv"
    rows = list(csv.DictReader(csv_path.open())) if csv_path.exists() else []
    metadata = json.loads((output_dir / "run_metadata.json").read_text())
    poses_by_idx = {p.pose_idx: p for p in scored_poses}

    return rows, metadata, poses_by_idx


@pytest.mark.slow
@pytest.mark.parametrize("case", _PEPSET_CASES, ids=[c.tag for c in _PEPSET_CASES])
class TestPepSetCrystalPoses:
    """TEST-03: Score crystal-structure peptide poses against real receptor pockets.

    For each PepSet complex, the reference peptide (crystal pose) is submitted as
    a single input pose against the unbound receptor pocket.  Since the pose is the
    actual binding geometry, Vina MUST return a negative score if the tool stack is
    functioning correctly.  A positive Vina score here indicates a real bug:
    receptor prep failure, grid misplacement, babel atom-type error, or a lingering
    issue from the RTX_DEBUG fixes (grids.py _LIGAND_TYPES, ligand.py -xr mode,
    receptor.py pdbfixer H-addition).

    Fixtures:
        tests/fixtures/{tag}/receptor_pocket.pdb  — pocket heavy atoms (H-stripped)
        tests/fixtures/{tag}/pose_000.pdb          — reference crystal pose (H-stripped)

    Sources: PepSet benchmark (Wen et al. 2020), families identical to RAPiDock
    training distribution.
    """

    def test_pipeline_completes(self, case: _PepSetCase, tmp_path: Path) -> None:
        """Pipeline must run without exception and write all required output files."""
        rows, metadata, _ = _run_pepset_case(case, tmp_path)

        assert metadata.get("status") == "complete", (
            f"{case.pdb_id} ({case.family}): run_metadata.json status="
            f"{metadata.get('status')!r} — pipeline did not reach Stage 4"
        )

        assert len(rows) >= 1, (
            f"{case.pdb_id}: ranked_poses.csv has no rows — "
            "all poses failed prep or scoring"
        )

        required_cols = {
            "rank", "hybrid_score", "vina_score", "ad4_score",
            "entropy_correction", "delta_g", "cluster_id",
            "pose_filename", "is_ad4_anomaly", "is_clipped",
        }
        assert required_cols.issubset(rows[0].keys()), (
            f"{case.pdb_id}: ranked_poses.csv missing columns: "
            f"{required_cols - rows[0].keys()}"
        )

    def test_vina_score_is_negative(self, case: _PepSetCase, tmp_path: Path) -> None:
        """Crystal-structure pose must score negative with Vina (physical sanity check).

        A positive Vina score for a crystal pose indicates: the pose is not in the
        binding site (grid misplaced), the receptor PDBQT prep failed, a steric
        clash was introduced by the receptor H-addition step, or a scoring bug.

        Expected range for well-prepared crystal poses: −4 to −12 kcal/mol.
        """
        rows, metadata, _ = _run_pepset_case(case, tmp_path)

        assert metadata.get("status") == "complete", (
            f"{case.pdb_id}: pipeline did not complete — cannot check Vina score"
        )
        assert len(rows) >= 1, (
            f"{case.pdb_id}: no rows in ranked_poses.csv"
        )

        best_vina = min(float(r["vina_score"]) for r in rows if r["vina_score"] not in ("", "None", "nan"))
        assert best_vina < 0.0, (
            f"{case.pdb_id} ({case.family}): best Vina score is {best_vina:+.2f} kcal/mol "
            f"(expected < 0 for crystal pose). "
            f"Likely causes: receptor prep failure, grid box misplaced, "
            f"or babel atom-type error. See RTX_DEBUG.md fixes C/D."
        )

    def test_ad4_score_is_negative(self, case: _PepSetCase, tmp_path: Path) -> None:
        """Crystal-structure pose must score negative with AD4 scoring.

        AD4 uses Gasteiger charges and a steeper repulsion term than Vina, so it
        is more sensitive to minor clashes introduced by H-addition.  A positive
        AD4 score with a negative Vina score indicates a clash in the H-added
        receptor — the RTX_DEBUG Fix C (grids.py _LIGAND_TYPES) or Fix H
        (OpenMM Quantity unit handling) may not be fully applied.
        """
        rows, metadata, _ = _run_pepset_case(case, tmp_path)

        assert metadata.get("status") == "complete", (
            f"{case.pdb_id}: pipeline did not complete"
        )
        assert len(rows) >= 1, (
            f"{case.pdb_id}: no rows in ranked_poses.csv"
        )

        # AD4 score may be None/nan if ad4 backend was skipped
        ad4_vals = [
            float(r["ad4_score"])
            for r in rows
            if r.get("ad4_score") not in ("", "None", "nan", None)
        ]
        if not ad4_vals:
            pytest.skip(
                f"{case.pdb_id}: no AD4 scores present — "
                "autogrid4 may not be on PATH (acceptable on macOS ARM)"
            )

        best_ad4 = min(ad4_vals)
        # AD4 is harder than Vina — flag anomaly but don't hard-fail (minor clashes
        # from pdbfixer H-addition are expected on the first run after fixes).
        if best_ad4 >= 0.0:
            pytest.xfail(
                f"{case.pdb_id} ({case.family}): AD4 score is {best_ad4:+.2f} kcal/mol "
                f"(expected < 0 for crystal pose). "
                f"Likely cause: H-clash from pdbfixer receptor prep. "
                f"See RTX_DEBUG.md Fix C (ligand types) and Fix H (OpenMM Quantity)."
            )

    def test_no_ad4_anomaly_flag(self, case: _PepSetCase, tmp_path: Path) -> None:
        """AD4 anomaly flag must be False for the best-ranked pose.

        is_ad4_anomaly=True means AD4 score > 0 — unphysical repulsion.  For a
        crystal pose this should not occur after RTX_DEBUG Fix C (extended
        _LIGAND_TYPES covering MET/TRP/HIS atom types).
        """
        rows, metadata, _ = _run_pepset_case(case, tmp_path)

        if metadata.get("status") != "complete" or not rows:
            pytest.skip(f"{case.pdb_id}: pipeline did not produce scored poses")

        best_row = rows[0]  # ranked_poses.csv is sorted by rank ascending
        anomaly = best_row.get("is_ad4_anomaly", "False")
        if anomaly in ("True", "true", "1"):
            pytest.xfail(
                f"{case.pdb_id}: best pose has is_ad4_anomaly=True — "
                f"AD4 score is positive for crystal pose. "
                f"Check grids.py _LIGAND_TYPES and receptor H-clash. "
                f"See RTX_DEBUG.md §Fix C."
            )
