"""End-to-end integration test for the MDM2/p53 complex (TEST-02).

Runs the full hybridock_pep pipeline using pre-generated fixture poses
(tests/fixtures/mdm2_p53/) and a minimal calibration fixture. Validates:
  - ranked_poses.csv written with correct columns and at least 1 row
  - best_pose.pdb written and non-empty
  - run_metadata.json written with status="complete"
  - Pipeline completes end-to-end without error

NOTE: The biological TEST-02 threshold (best hybrid_score < -3.0 kcal/mol)
requires a realistic MDM2 receptor fixture.  receptor_tiny.pdb is a 3-atom
placeholder positioned 25 Å from the fixture poses; Vina returns ~0 kcal/mol
for it regardless of pose quality.  The threshold is validated by the full
benchmark suite (scripts/benchmark.py) against real receptor data.

Tagged @pytest.mark.slow — requires the full score-env tool stack:
Vina ≥ 1.2.5, ADFRsuite on PATH.

Run with: pytest -m slow tests/test_e2e.py
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _make_e2e_config(output_dir: Path):
    """Build a DockConfig for MDM2/p53 using the receptor_tiny.pdb placeholder.

    Uses receptor_tiny.pdb (3 ALA atoms) for pipeline wiring tests only.
    box_size=60 is required to cover extended backbone poses (~44 Å span).

    Args:
        output_dir: Destination directory for ranked_poses.csv, best_pose.pdb,
            run_metadata.json.

    Returns:
        Validated DockConfig instance.
    """
    from hybridock_pep.models import DockConfig

    return DockConfig(
        peptide_sequence="ETFSDLWKLLPE",
        receptor_path=FIXTURES_DIR / "receptor_tiny.pdb",
        site_coords=(26.4, 3.5, -5.6),
        # box_size=60 covers the full span of extended 12-mer backbone poses
        # (~44 Å) generated by RAPiDock without CONECT records, which babel
        # cannot connect into a single molecule. 30 Å is too small and causes
        # "ligand outside grid box" errors on most fixture poses.
        box_size=60.0,
        n_samples=25,
        output_dir=output_dir,
        seed=42,
    )


@pytest.mark.slow
class TestMDM2P53Integration:
    """Full pipeline integration test on the MDM2/p53 complex.

    Requires Vina, Meeko, ADFRsuite, and score-env fully installed.
    Skipped automatically when pytest is run without -m slow.
    """

    def test_pipeline_runs_end_to_end(self, tmp_path: Path) -> None:
        """Run the full pipeline on 25 MDM2/p53 fixture poses; assert outputs are correct.

        Validates pipeline wiring (TEST-02 structural checks):
          - ranked_poses.csv produced with required columns
          - best_pose.pdb written and non-empty
          - run_metadata.json has status="complete"
          - delta_g == hybrid_score in every row

        NOTE: The biological TEST-02 threshold (hybrid_score < -3.0 kcal/mol)
        is NOT checked here because receptor_tiny.pdb is a placeholder 25 Å
        from the fixture poses.  The threshold is validated by the benchmark
        suite against the real MDM2 receptor.
        """
        from hybridock_pep import driver

        poses_dir = FIXTURES_DIR / "mdm2_p53"
        cal_path = FIXTURES_DIR / "mdm2_calibration.json"
        output_dir = tmp_path / "mdm2_run"
        config = _make_e2e_config(output_dir)

        scored_poses, cluster_result = driver.run_dock(
            config=config,
            input_poses_dir=poses_dir,
            calibration_path=cal_path,
        )

        # --- Assert: ranked_poses.csv exists with correct structure ---
        csv_path = output_dir / "ranked_poses.csv"
        assert csv_path.exists(), "ranked_poses.csv must be created by Stage 4"

        rows = list(csv.DictReader(csv_path.open()))
        assert 1 <= len(rows) <= 10, (
            f"ranked_poses.csv should have 1–10 rows; got {len(rows)}"
        )

        required_cols = {
            "rank", "hybrid_score", "vina_score", "ad4_score",
            "entropy_correction", "delta_g", "cluster_id",
            "pose_filename", "is_ad4_anomaly", "is_clipped",
        }
        assert required_cols.issubset(rows[0].keys()), (
            f"Missing columns: {required_cols - rows[0].keys()}"
        )

        # --- Assert: hybrid_score is a finite float (scoring ran without crash) ---
        # The biological threshold (< -3.0 kcal/mol) requires the real MDM2
        # receptor; with receptor_tiny.pdb the Vina score is ~0 by design.
        best_hybrid = min(float(r["hybrid_score"]) for r in rows)
        assert isinstance(best_hybrid, float) and best_hybrid < 1e6, (
            f"hybrid_score is not a finite float: {best_hybrid}"
        )

        # --- Assert: best_pose.pdb exists and is non-empty ---
        best_pdb = output_dir / "best_pose.pdb"
        assert best_pdb.exists(), "best_pose.pdb must be written by Stage 4"
        assert best_pdb.stat().st_size > 0, "best_pose.pdb must not be empty"

        # --- Assert: run_metadata.json written with status=complete ---
        metadata_path = output_dir / "run_metadata.json"
        assert metadata_path.exists(), "run_metadata.json must exist"
        metadata = json.loads(metadata_path.read_text())
        assert metadata.get("status") == "complete", (
            f"run_metadata.json status should be 'complete', got {metadata.get('status')!r}"
        )

        # --- Assert: delta_g == hybrid_score in every row (D-04) ---
        for row in rows:
            assert row["delta_g"] == row["hybrid_score"], (
                f"delta_g ({row['delta_g']}) != hybrid_score ({row['hybrid_score']}) "
                f"for rank {row['rank']}"
            )
