#!/usr/bin/env python3
"""Bundle the browser UI into one JS file and one CSS file.

    python3 scripts/build_web.py            # rebuild src/hybridock_pep/web/static/dist/
    python3 scripts/build_web.py --check    # exit 1 if dist/ is stale (used by the tests; needs no Node)

Why bundle? ``hybridock-pep serve`` is a stdlib server that answers HTTP/1.0 with a small listen queue, so
every file the page loads is a new connection. The ~30 separate ES modules of the source tree could overflow
that queue when the machine was busy (mid-docking), and the page then failed to start with
ERR_CONNECTION_RESET. One JS file and one CSS file make that a non-issue. The readable modules under
``static/js/app/`` stay the source of truth; ``static/dist/`` is generated from them.

JS is bundled with esbuild, fetched on demand by ``npx`` (Node 18+ needed only to *rebuild*, never to run).
CSS is concatenated in a fixed order. Both outputs start with a hash of their sources so a stale bundle is
detected without Node.
"""
from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

STATIC = Path(__file__).resolve().parent.parent / "src" / "hybridock_pep" / "web" / "static"
DIST = STATIC / "dist"
CSS_ORDER = ["fonts", "tokens", "base", "layout", "components", "screens"]
ESBUILD = "esbuild@0.25.0"
HEADER = "/* GENERATED by scripts/build_web.py from {what}. Do not edit. source-hash: {digest} */\n"


def digest(paths: list[Path]) -> str:
    h = hashlib.sha256()
    for p in sorted(paths):
        h.update(p.relative_to(STATIC).as_posix().encode())
        h.update(p.read_bytes().replace(b"\r\n", b"\n"))  # a Windows checkout may have CRLF; the hash must not care
    return h.hexdigest()[:16]


def js_sources() -> list[Path]:
    return sorted((STATIC / "js" / "app").rglob("*.mjs"))


def css_sources() -> list[Path]:
    return [STATIC / "css" / "app" / f"{name}.css" for name in CSS_ORDER]


def current_hashes() -> tuple[str, str]:
    return digest(js_sources()), digest(css_sources())


def stored_hash(path: Path) -> str | None:
    if not path.exists():
        return None
    first = path.read_text(encoding="utf-8").split("\n", 1)[0]
    return first.rsplit("source-hash: ", 1)[-1].split(" ")[0] if "source-hash:" in first else None


def is_fresh() -> bool:
    js, css = current_hashes()
    return stored_hash(DIST / "app.mjs") == js and stored_hash(DIST / "app.css") == css


def build() -> None:
    js_hash, css_hash = current_hashes()
    DIST.mkdir(exist_ok=True)

    css = "\n".join(f"/* {p.name} */\n{p.read_text(encoding='utf-8')}" for p in css_sources())
    (DIST / "app.css").write_text(HEADER.format(what="static/css/app (all stylesheets)", digest=css_hash) + css, encoding="utf-8")

    npx = shutil.which("npx")
    if npx is None:
        sys.exit("Rebuilding the JS bundle needs Node.js (npx). Install Node 18+ and run this again.")
    out = DIST / "app.mjs.tmp"
    subprocess.run(
        [npx, "--yes", ESBUILD, str(STATIC / "js" / "app" / "main.mjs"), "--bundle", "--format=esm",
         "--target=es2022", "--legal-comments=none", f"--outfile={out}", "--log-level=warning"],
        check=True,
    )
    body = out.read_text(encoding="utf-8")
    out.unlink()
    (DIST / "app.mjs").write_text(HEADER.format(what="static/js/app (all modules)", digest=js_hash) + body, encoding="utf-8")
    print(f"built {DIST / 'app.mjs'} ({len(body) // 1024} KB) and {DIST / 'app.css'}")


if __name__ == "__main__":
    if "--check" in sys.argv:
        ok = is_fresh()
        print("dist/ is up to date" if ok else "dist/ is STALE: run python3 scripts/build_web.py")
        sys.exit(0 if ok else 1)
    build()
