#!/usr/bin/env python3
"""Extend confidence training data from 491 to ~1000 complexes.

Takes complexes from benchmark300 and v7_train_balanced that are NOT
already in confidence_training_500.csv, generates poses + RMSD labels,
and appends them to the existing benchmark_results.json.

Strategy:
  - Source 1: benchmark300 complexes not in existing confidence data (~200 new)
  - Source 2: well-scoring v6 training complexes not in confidence data (~300 new)
  - Target: ~1000 total (491 existing + ~509 new)
  - n_samples=5 poses per complex (fast; confidence model trains on RMSD distributions)

Uses pretrained model for pose generation (same as existing data; keeps
distribution consistent for the confidence model).

Usage:
    conda run -n score-env python3 scripts/expand_confidence_data.py \
        --n-new 509 \
        --n-samples 5 \
        --out-json logs/confidence_training_data/benchmark_results_expanded.json

    # After verifying, replace the original:
    # cp logs/confidence_training_data/benchmark_results_expanded.json \\
    #    logs/confidence_training_data/benchmark_results.json
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import random
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

EXISTING_JSON     = REPO / "logs" / "confidence_training_data" / "benchmark_results.json"
EXISTING_CSV      = REPO / "data" / "confidence_training_500.csv"
BENCH300_CSV      = REPO / "data" / "benchmark300.csv"
V7_TRAIN_CSV      = REPO / "data" / "v7_train_balanced.csv"    # generated by curate_v7_training_data.py
RAPIDOCK_DIR      = REPO / "third_party" / "RAPiDock"
RUN_SHIM          = REPO / "src" / "hybridock_pep" / "sampling" / "run_rapidock.py"
BASE_MODEL_DIR    = (
    REPO / "third_party" / "RAPiDock_finetuned" /
    "train_models" / "CGTensorProductEquivariantModel"
)
PRETRAINED_CKPT   = BASE_MODEL_DIR / "rapidock_local.pt"

log = logging.getLogger(__name__)


def _find_rapidock_python() -> str:
    for base in [Path.home() / "miniconda3", Path.home() / "miniforge3",
                 Path.home() / "anaconda3", Path("/opt/conda")]:
        p = base / "envs" / "rapidock" / "bin" / "python3"
        if p.exists():
            return str(p)
    raise RuntimeError("rapidock conda env not found")


def _ca_coords_from_pdb(pdb: Path) -> np.ndarray:
    coords = []
    for ln in pdb.read_text().splitlines():
        if ln.startswith(("ATOM", "HETATM")) and ln[12:16].strip() == "CA":
            try:
                coords.append([float(ln[30:38]), float(ln[38:46]), float(ln[46:54])])
            except ValueError:
                continue
    return np.array(coords) if coords else np.zeros((0, 3))


def _ca_rmsd(pose_pdb: Path, crystal_ca: np.ndarray) -> Optional[float]:
    pose_ca = _ca_coords_from_pdb(pose_pdb)
    if len(pose_ca) == 0 or len(crystal_ca) == 0:
        return None
    n = min(len(pose_ca), len(crystal_ca))
    return float(np.sqrt(((pose_ca[:n] - crystal_ca[:n]) ** 2).sum(axis=1).mean()))


def _build_candidate_list(existing_names: set[str], n_new: int, seed: int) -> list[dict]:
    """Build list of new complexes to score, excluding existing ones."""
    candidates: list[dict] = []
    rng = random.Random(seed)

    # Source 1: benchmark300
    if BENCH300_CSV.exists():
        bench = pd.read_csv(BENCH300_CSV)
        new_bench = bench[~bench["name"].isin(existing_names)]
        new_bench = new_bench[
            new_bench["receptor"].apply(lambda p: Path(p).exists()) &
            new_bench["peptide_pdb"].apply(lambda p: Path(p).exists())
        ]
        for _, r in new_bench.iterrows():
            candidates.append({
                "name": r["name"],
                "receptor": r["receptor"],
                "peptide_pdb": r["peptide_pdb"],
                "seq": r.get("seq", ""),
                "ss_class": r.get("ss_class", "UNKNOWN"),
                "length_bucket": r.get("length_bucket", "unknown"),
            })
        log.info("Source bench300: %d new candidates", len(candidates))

    # Source 2: v7 training data (if available)
    if V7_TRAIN_CSV.exists():
        v7 = pd.read_csv(V7_TRAIN_CSV)
        rec_col = "protein_description" if "protein_description" in v7.columns else "receptor"
        pep_col = "peptide_description" if "peptide_description" in v7.columns else "peptide_pdb"
        name_col = "complex_name" if "complex_name" in v7.columns else "name"
        new_v7 = v7[~v7[name_col].isin(existing_names)]
        new_v7 = new_v7[
            new_v7[rec_col].apply(lambda p: Path(p).exists()) &
            new_v7[pep_col].apply(lambda p: Path(p).exists())
        ]
        before = len(candidates)
        for _, r in new_v7.iterrows():
            candidates.append({
                "name": r[name_col],
                "receptor": r[rec_col],
                "peptide_pdb": r[pep_col],
                "seq": r.get("seq", ""),
                "ss_class": r.get("ss_class", "UNKNOWN"),
                "length_bucket": r.get("length_bucket", "unknown"),
            })
        log.info("Source v7_train: %d new candidates", len(candidates) - before)

    # Stratified sample up to n_new
    rng.shuffle(candidates)

    # Try to balance SS classes
    by_ss: dict[str, list] = {}
    for c in candidates:
        by_ss.setdefault(c["ss_class"], []).append(c)

    selected: list[dict] = []
    per_ss = max(1, n_new // max(len(by_ss), 1))
    for ss_list in by_ss.values():
        selected.extend(ss_list[:per_ss])
    # Fill remainder
    remaining = [c for c in candidates if c not in selected]
    rng.shuffle(remaining)
    selected.extend(remaining[:max(0, n_new - len(selected))])

    return selected[:n_new]


def run_inference_and_rmsd(
    complex_info: dict,
    out_dir: Path,
    n_samples: int,
    seed: int,
    rapidock_python: str,
) -> Optional[dict]:
    """Run pretrained inference + RMSD for one complex. Returns result dict or None."""
    name = complex_info["name"]
    receptor_pdb = Path(complex_info["receptor"])
    crystal_pdb  = Path(complex_info["peptide_pdb"])
    seq          = complex_info.get("seq", "")

    # Infer seq from crystal PDB if missing
    if not seq:
        three_to_one = {
            "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
            "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
            "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
            "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V",
        }
        seen: list[str] = []
        last_res = None
        for ln in crystal_pdb.read_text().splitlines():
            if ln.startswith("ATOM") and ln[12:16].strip() == "CA":
                res = ln[17:20].strip()
                resid = ln[22:26].strip()
                if resid != last_res:
                    seen.append(three_to_one.get(res, "X"))
                    last_res = resid
        seq = "".join(seen)

    if not seq:
        log.warning("[%s] could not determine sequence, skipping", name)
        return None

    complex_out = out_dir / name
    done_marker = complex_out / "inference_done.json"

    if not done_marker.exists():
        complex_out.mkdir(parents=True, exist_ok=True)
        raw_dir = complex_out / "poses_raw"
        tmp_model = complex_out / "_model_dir"
        tmp_model.mkdir(exist_ok=True)
        yml_src = BASE_MODEL_DIR / "model_parameters.yml"
        if yml_src.exists():
            shutil.copy2(yml_src, tmp_model / "model_parameters.yml")
        link = tmp_model / PRETRAINED_CKPT.name
        if not link.exists():
            link.symlink_to(PRETRAINED_CKPT.resolve())

        cmd = [
            rapidock_python, str(RUN_SHIM),
            "--peptide",       seq,
            "--receptor",      str(receptor_pdb.resolve()),
            "--output-dir",    str(raw_dir.resolve()),
            "--n-samples",     str(n_samples),
            "--seed",          str(seed),
            "--rapidock-dir",  str(RAPIDOCK_DIR.resolve()),
            "--model-dir",     str(tmp_model.resolve()),
            "--ckpt",          PRETRAINED_CKPT.name,
            "--scoring-function", "none",
        ]
        t0 = time.time()
        proc = subprocess.run(cmd, capture_output=True, text=True)
        elapsed = time.time() - t0
        if proc.returncode != 0:
            log.warning("[%s] RAPiDock exit %d in %.0fs", name, proc.returncode, elapsed)

        raw_inner = raw_dir / "poses_raw"
        if not raw_inner.exists():
            raw_inner = raw_dir
        rank_files = sorted(
            raw_inner.glob("rank*.pdb"),
            key=lambda p: int(re.search(r"rank(\d+)", p.stem).group(1)),  # type: ignore[union-attr]
        )
        poses_dir = complex_out / "poses"
        poses_dir.mkdir(exist_ok=True)
        for i, src in enumerate(rank_files):
            shutil.copy2(src, poses_dir / f"pose_{i}.pdb")

        done_marker.write_text(json.dumps({"n_poses": len(rank_files), "elapsed_s": elapsed}))
        log.info("[%s] %d poses in %.0fs", name, len(rank_files), elapsed)

    poses = sorted((complex_out / "poses").glob("pose_*.pdb"))
    if not poses:
        log.warning("[%s] no poses found after inference", name)
        return None

    crystal_ca = _ca_coords_from_pdb(crystal_pdb)
    ref_rmsds = []
    for p in poses:
        r = _ca_rmsd(p, crystal_ca)
        ref_rmsds.append(r if r is not None else float("nan"))

    return {
        "poses_dir": str(complex_out / "poses"),
        "ref_rmsds": ref_rmsds,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n-new",     type=int, default=509,
                    help="Number of new complexes to add (default 509 → ~1000 total)")
    ap.add_argument("--n-samples", type=int, default=5,
                    help="Poses per complex for confidence training (default 5)")
    ap.add_argument("--seed",      type=int, default=42)
    ap.add_argument("--out-json",  default=str(REPO / "logs" / "confidence_training_data" /
                                               "benchmark_results_expanded.json"),
                    help="Output JSON path (default: …/benchmark_results_expanded.json)")
    ap.add_argument("--poses-dir", default=str(REPO / "logs" / "confidence_training_data" / "new_poses"),
                    help="Directory to store generated poses")
    args = ap.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")

    # Load existing data
    existing: dict = {}
    if EXISTING_JSON.exists():
        with open(EXISTING_JSON) as fh:
            existing = json.load(fh)
    log.info("Existing confidence data: %d complexes", len(existing))

    existing_names = set(existing.keys())
    candidates = _build_candidate_list(existing_names, args.n_new, args.seed)
    log.info("Candidates to process: %d", len(candidates))

    if not candidates:
        log.info("No new candidates found — nothing to do")
        return

    rapidock_python = _find_rapidock_python()
    poses_dir = Path(args.poses_dir)
    poses_dir.mkdir(parents=True, exist_ok=True)

    out_json = Path(args.out_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)

    # Start from existing data
    results = dict(existing)

    for i, info in enumerate(candidates):
        name = info["name"]
        if name in results:
            continue
        log.info("[%d/%d] %s", i + 1, len(candidates), name)
        result = run_inference_and_rmsd(
            complex_info=info,
            out_dir=poses_dir,
            n_samples=args.n_samples,
            seed=args.seed,
            rapidock_python=rapidock_python,
        )
        if result is not None:
            results[name] = {"pretrained": result}

        # Checkpoint every 20 complexes
        if (i + 1) % 20 == 0:
            out_json.write_text(json.dumps(results, indent=2))
            log.info("Checkpoint: %d complexes total", len(results))

    out_json.write_text(json.dumps(results, indent=2))
    log.info("Done. Total complexes: %d → %s", len(results), out_json)
    print(f"\nExpanded confidence training data: {len(existing)} → {len(results)} complexes")
    print(f"Output: {out_json}")
    print("To use: cp {out_json} logs/confidence_training_data/benchmark_results.json")
    print("Then re-run confidence training.")


if __name__ == "__main__":
    main()
